export const movies = [
  {
    title: "Das Geheimnis von Altura",
    year: 2024,
    length: "120 Minuten",
    actors: ["Lena Herzog", "Maximilian Schröder", "Sophia Neumann"],
    poster: "/images/Altura.png",
  },
  {
    title: "Sternenwanderer",
    year: 2025,
    length: "143 Minuten",
    actors: ["Hannah Fischer", "Julian Becker", "Lara Weber"],
    poster: "/images/Sternenwanderer.png",
  },
  {
    title: "Flüsternde Schatten",
    year: 2023,
    length: "105 Minuten",
    actors: ["Emilie Schmidt", "Niklas Hoffmann", "Anna Meyer"],
    poster: "/images/Schatten.png",
  },
  {
    title: "Die letzte Ebene",
    year: 2026,
    length: "132 Minuten",
    actors: ["David Wagner", "Sarah Bauer", "Leon Schwarz"],
    poster: "/images/Ebene.png",
  },
  {
    title: "Chroniken von Morgen",
    year: 2027,
    length: "117 Minuten",
    actors: ["Marie Müller", "Tobias Lang", "Lisa Braun"],
    poster: "/images/Chroniken.png",
  },
  {
    title: "Die Wächter des Verborgenen",
    year: 2028,
    length: "150 Minuten",
    actors: ["Felix Zimmermann", "Charlotte Koch", "Alexander Krause"],
    poster: "/images/Waechter.png",
  },
  {
    title: "Nebel über Neustadt",
    year: 2029,
    length: "98 Minuten",
    actors: ["Nora Richter", "Simon Wolf", "Julia Hartmann"],
    poster: "/images/Nebel.png",
  },
  {
    title: "Das Lächeln der Medusa",
    year: 2030,
    length: "136 Minuten",
    actors: ["Max Müller", "Katharina Schmid", "Tim Schneider"],
    poster: "/images/Medusa.png",
  },
  {
    title: "Echo des Vergessens",
    year: 2022,
    length: "123 Minuten",
    actors: ["Anna Lehmann", "Fabian Engel", "Lea Frank"],
    poster: "/images/Echo.png",
  },
  {
    title: "Der Traum von Unendlichkeit",
    year: 2024,
    length: "140 Minuten",
    actors: ["Lukas Wagner", "Mia Sommer", "Jan Schmidt"],
    poster: "/images/Traum.png",
  },
];
